### ISSUE TITLE
Add a callback for whenever cssText changes

### ISSUE THREAD

**Issue by domenic** [chad3814/CSSStyleDeclaration#28]
Or maybe just whenever a property is modified?

I'm overhauling some of jsdom's style attribute mess, and I think such a hook would allow me a much cleaner architecture. In particular I want to reflect [the spec's](http://dev.w3.org/csswg/cssom/#the-elementcssinlinestyle-interface):

> Mutating the declarations must set the style content attribute on the context object to the serialization of the declarations.

I think for now I will override _setProperty, but I don't like overwriting private members... some kind of callback I could pass to the CSSStyleDeclaration constructor would be best.

**Comment by chad3814** [comment]
sure, I can add that

**Comment by chad3814** [comment]
would you rather a callback, or have it implement EventEmitter and emit on a change?

**Comment by domenic** [comment]
I think callback would be better since real CSSStyleDeclarations don't have `on`/`removeListener`/etc. methods.

**Comment by chad3814** [comment]
I published 0.2.25 with an optional onChange callback to the constructor; the callback will be called every time the cssText changes, with the changed text as the only argument

**Comment by domenic** [comment]
Thanks; incorporated into jsdom!!
