### ISSUE TITLE
Implement `float`

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [chad3814/CSSStyleDeclaration#29]
It seems that I can set/get `cssFloat`, but not `float`.

As I read the CSSOM standard, this should be possible. The browsers allow you to do this too:

```javascript
node.style.float = 'left'; // might need ['float'] in old ES implementations
node.style.cssFloat === 'left; // true
```

**Comment by chad3814** [comment]
published 0.2.26 to fix this
